import { parse } from 'node-html-parser';

export const ParsePage = () => {
  const htmlString =
    '<!DOCTYPE html>\n<html lang="ja">\n <head>\n <meta charset="UTF-8" />\n <meta name="viewport" content="width=device-width, initial-scale=1.0" />\n <link\n rel="stylesheet"\n href="https://cdn.jsdelivr.net/npm/@ionic/core@6.1/css/ionic.bundle.css"\n />\n <script src="https://cdn.jsdelivr.net/npm/@ionic/core@6.1/dist/ionic/ionic.js"></script>\n </head>\n <body>\n <ion-modal is-open="true" mode="ios" style="--height: 100%; --width: 100%">\n <ion-header translucent>\n <ion-toolbar>\n <ion-title>マルチステップ検証シナリオ</ion-title>\n <ion-buttons slot="end">\n <ion-button id="dismiss">×</ion-button>\n </ion-buttons>\n </ion-toolbar>\n </ion-header>\n <ion-content fullscreen>\n <ion-grid>\n <ion-row class="ion-padding">\n <ion-col size="8">\n <ion-row>\n <ion-col size="12" class="ion-margin-bottom">\n <ion-text>\n <strong>step_01</strong>\n </ion-text>\n </ion-col>\n <ion-col size="12">\n <ion-text>ボタンを押してください</ion-text>\n </ion-col>\n </ion-row>\n </ion-col>\n <ion-col size="6">\n <ion-button id="show_favorite" expand="block">step_02a</ion-button>\n </ion-col>\n <ion-col size="6">\n <ion-button id="show_category" expand="block">step_02b</ion-button>\n </ion-col>\n <ion-col size="6">\n <ion-button id="close" expand="block" color="light">閉じる</ion-button>\n </ion-col> \n </ion-row>\n </ion-grid>\n </ion-content>\n </ion-modal>\n\n <script>\n var showFavoriteButton = document.getElementById("show_favorite");\n showFavoriteButton.addEventListener(\n "click",\n function () {\n sprocketSdk.trigger("button.click", "show_favorite");\n },\n false\n );\n\n var showCategoryButton = document.getElementById("show_category");\n showCategoryButton.addEventListener(\n "click",\n function () {\n sprocketSdk.trigger("button.click", "show_category");\n },\n false\n );\n \n var closeButton = document.getElementById("close");\n closeButton.addEventListener(\n "click",\n function () {\n sprocketSdk.trigger("button.click", "close");\n },\n false\n );\n\n var dismissButton = document.getElementById("dismiss");\n dismissButton.addEventListener(\n "click",\n function () {\n sprocketSdk.trigger("dismiss", "");\n },\n false\n );\n </script>\n </body>\n</html>\n';
  const parsed = parse(htmlString);
  const parsedString = parsed.toString();
  console.log(parsed, parsed.querySelector('#dismiss'), parsedString);

  return <div />;
};
